### PR TITLE
Add current working directory to @INC

### PR DESCRIPTION
**Pull request by kholia**
See https://github.com/magnumripper/JohnTheRipper/issues/2988 for the details.

There might be a better fix but I don't know any Perl.

### CODE REVIEW

**Comment by jfoug** [comment]
What bug is this fixing?   i have no problems with it, if it causes no other issues, but I am not sure why this change is needed.....

**Comment by roycewilliams** [comment]
Not knowing any better, would it make more sense to explicitly include the needed modules? This has the additional benefit of making the dependencies explicit and self-documenting.

**Comment by kholia** [comment]
> What bug is this fixing?

From https://github.com/magnumripper/JohnTheRipper/issues/2988,

It seems that `@INC` does not have the current working directory path in it (anymore). I am guessing that this is due to a recent security fix for Perl involving loading of modules from CWD insecurely.

Update: https://wiki.gentoo.org/wiki/Project:Perl/Dot-In-INC-Removal has more information on this topic.

```
$ perl --version

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi
(with 28 registered patches, see perl -V for more detail)

Copyright 1987-2017, Larry Wall
```

**Comment by kholia** [comment]
The dependencies are already explicit,

```
$ cat jtrts.pl | head -8
#!/usr/bin/perl -w
use strict;
use lib ".";

use Getopt::Long;
use jtrts_inc;  # <---- dependency here 
use Digest::MD5;
use MIME::Base64;
```

The "bug" is that the modern Perl versions just don't look for dependencies in the current working directory anymore.

**Comment by roycewilliams** [comment]
To clarify, I'm suggesting that both module and location be enumerated and made explicit, as in:

`require './jtrs_inc';`

There may be ramifications of that of which I am not aware, though.

**Comment by kholia** [comment]
```
$ cat jtrts.pl | head -8
#!/usr/bin/perl -w
use strict;

use Getopt::Long;
require './jtrts_inc';  # <------- new change here
use Digest::MD5;
use MIME::Base64;
use List::Util qw/shuffle/;
```

```
$ ./jtrts.pl -noprelims  --type rsvp
Can't locate ./jtrts_inc at ./jtrts.pl line 5.
```

This change doesn't seem to be working regardless of the `use lib "."` change.

**Comment by roycewilliams** [comment]
Ah, I see - it's a little more complex than that (and therefore maybe not work the trouble?)

https://stackoverflow.com/questions/185114/how-do-i-use-a-perl-module-in-a-directory-not-in-inc

**Comment by kholia** [comment]
Many of the solutions boil down to modifying `@INC`, and this is exactly what the `use lib "."` line (from the patch) does in a relatively simple way.

**Comment by jfoug** [comment]
Thank you for the information and links @kholia   Yes, the reason it probably just 'works' for me, is I am running on perl that does not have this change. So what we have really done is within this code, to tell perl explicit to revert to its p[rior behavior.   Sounds ok to me.

**Pull request merged**
